const axios = require("axios");

// const courses = [
//   {
//     prefix: "CSCE",
//     shortNumber: "102",
//     longNumber: "1000",
//     title: "Introduction to Computers and their Applications (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "106",
//     longNumber: "1001",
//     title: "Fundamentals of Computing I (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "110",
//     longNumber: "1101",
//     title: "Fundamentals of Computing II (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "000",
//     longNumber: "1102",
//     title: "Fundamentals of Computing II Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "321",
//     longNumber: "2202",
//     title: "Analysis and Design of Algorithms (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "000",
//     longNumber: "2203",
//     title: "Analysis and Design of Algorithms Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "230",
//     longNumber: "2301",
//     title: "Digital Design I (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "239L",
//     longNumber: "2302",
//     title: "Digital Design I Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "231",
//     longNumber: "2303",
//     title: "Computer Organization and Assembly Language Programming (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "253",
//     longNumber: "2501",
//     title: "Fundamentals of Database Systems (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "201",
//     longNumber: "2502",
//     title: "Information Technology (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "315",
//     longNumber: "3101",
//     title: "Programming Language (1-3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "316",
//     longNumber: "3102",
//     title: "Programming in Java (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "317",
//     longNumber: "3103",
//     title: "Object Oriented Programming (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "325",
//     longNumber: "3104",
//     title: "Concepts of Programming Languages (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "330",
//     longNumber: "3301",
//     title: "Computer Architecture (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "339L",
//     longNumber: "3302",
//     title: "Computer Architecture Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "332",
//     longNumber: "3303",
//     title: "Fundamental Microelectronics (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "337",
//     longNumber: "3304",
//     title: "Digital Design II (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "333",
//     longNumber: "3311",
//     title: "Data and Computer Communications (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "435",
//     longNumber: "3312",
//     title: "Computer Networks (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "439L",
//     longNumber: "3313",
//     title: "Computer Networks Lab (1 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "345",
//     longNumber: "3401",
//     title: "Operating Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "000",
//     longNumber: "3402",
//     title: "Operating Systems Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "342",
//     longNumber: "3421",
//     title: "Fundamentals of Computing and Communication Systems (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "346",
//     longNumber: "3422",
//     title: "Introduction to Information Security (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "465",
//     longNumber: "3601",
//     title: "Artificial Intelligence (3 cr.)",
//     taken: true,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "363",
//     longNumber: "3611",
//     title: "Digital Signal Processing (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "341",
//     longNumber: "3701",
//     title: "Software Engineering (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "447",
//     longNumber: "4101",
//     title: "Compiler Design (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "422",
//     longNumber: "4201",
//     title: "Theory of Computing (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "432",
//     longNumber: "4301",
//     title: "Embedded Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "438L",
//     longNumber: "4302",
//     title: "Embedded Systems Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "437",
//     longNumber: "4313",
//     title: "Local and Metropolitan Area Networks (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "436L",
//     longNumber: "4314",
//     title: "Local Area Networks Lab (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "445",
//     longNumber: "4411",
//     title: "Fundamentals of Distributed Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "446",
//     longNumber: "4421",
//     title: "Computer Security (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "453",
//     longNumber: "4501",
//     title: "Database Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "456",
//     longNumber: "4502",
//     title: "Design of Web-based Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "401",
//     longNumber: "4503",
//     title: "Internet-based Information Systems (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "427",
//     longNumber: "4602",
//     title: "Introduction to Artificial Neural Networks (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "000",
//     longNumber: "4603",
//     title: "Fundamentals of Computer Vision (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "000",
//     longNumber: "4604",
//     title: "Practical Machine Deep Learning (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "455",
//     longNumber: "4621",
//     title: "Computer Graphics (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "441",
//     longNumber: "4701",
//     title: "Object-Oriented Analysis and Design (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "448",
//     longNumber: "4702",
//     title: "Secure Systems Engineering (3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "495",
//     longNumber: "4910",
//     title: "Guided Studies in Computer Science and Engineering (1-3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "485",
//     longNumber: "4930",
//     title: "Selected Topics in Computer Science and Engineering (1-3 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "490",
//     longNumber: "4950",
//     title: "Industrial Training (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "491",
//     longNumber: "4980",
//     title: "Senior Project I (1 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "492",
//     longNumber: "4981",
//     title: "Senior Project II (2 cr.)",
//     taken: false,
//   },
//   {
//     prefix: "CSCE",
//     shortNumber: "525",
//     longNumber: "5221",
//     title: "Algorithms and Complexity Theory (3 cr.)",
//     taken: false,
//   },

//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "529",
//   //     longNumber: "5222",
//   //     title: "Design and Analysis of Parallel Algorithms (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "530",
//   //     longNumber: "5231",
//   //     title: "Advanced Processor Architecture (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "535",
//   //     longNumber: "5232",
//   //     title: "High Speed Networks (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "545",
//   //     longNumber: "5241",
//   //     title: "Distributed Systems (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "532",
//   //     longNumber: "5242",
//   //     title: "Parallel Computer Architecture (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "000",
//   //     longNumber: "5243",
//   //     title: "Information and System Security (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "000",
//   //     longNumber: "5245",
//   //     title: "Embedded Real-Time Systems (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "565",
//   //     longNumber: "5261",
//   //     title: "Advanced Artificial Intelligence (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "527",
//   //     longNumber: "5262",
//   //     title: "Neural Networks and Genetic Algorithms (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "561",
//   //     longNumber: "5263",
//   //     title: "Knowledge Engineering (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "569",
//   //     longNumber: "5264",
//   //     title: "Natural Language Processing and Machine Translation (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "564",
//   //     longNumber: "5265",
//   //     title: "Web Mining (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "567",
//   //     longNumber: "5266",
//   //     title: "Computer Vision (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "563",
//   //     longNumber: "5267",
//   //     title: "Digital Image Processing (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "555",
//   //     longNumber: "5268",
//   //     title: "Computer Graphics and Animation (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "000",
//   //     longNumber: "5269",
//   //     title: "Pattern Analysis (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "541",
//   //     longNumber: "5271",
//   //     title: "Advanced Software Engineering (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "543",
//   //     longNumber: "5272",
//   //     title: "Advanced Software Quality (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "000",
//   //     longNumber: "5910",
//   //     title:
//   //       "Independent Studies in Computer Science and Engineering (1-3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "585",
//   //     longNumber: "5930",
//   //     title: "Selected Topics in Computer Science and Engineering (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "590",
//   //     longNumber: "5940",
//   //     title: "Seminar (1 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "591",
//   //     longNumber: "5980",
//   //     title: "Capstone Project in Computing (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "599",
//   //     longNumber: "5981",
//   //     title: "Graduate Thesis (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "642",
//   //     longNumber: "6231",
//   //     title: "Mobile and Pervasive Computing (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "664",
//   //     longNumber: "6261",
//   //     title: "Advanced Data Mining (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "692",
//   //     longNumber: "6930",
//   //     title: "Advanced Selected Topics in Computer Science (3 cr.)",
//   //   taken:false},
//   //   {
//   //     prefix: "CSCE",
//   //     shortNumber: "699",
//   //     longNumber: "6980",
//   //     title: "Research Guidance Dissertation (3 cr.)",
//   //   taken:false},
// ];
const baseUrl = "http://localhost:5000/api/courses";
const getAllCourses = async () => {
  const { data: courses } = await axios.get(baseUrl);
  console.log(courses);
  return courses;
};

const getCourse = async (course_id) => {
  const { data: course } = await axios.get(baseUrl + "/" + course_id);
  return course;
};

export { getAllCourses, getCourse };
